import { getAuthDatabase,getRequestUser,isSameOrigin } from "@/lib/auth";
import { loadSubmission,parseSubmission,replaceSubmissionContent,validateForSubmission } from "@/lib/submissions";

export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){const [db,user,{id}]=await Promise.all([getAuthDatabase(),getRequestUser(request),params]);if(!db||!user)return Response.json({error:"Unauthorized"},{status:401});const submission=await loadSubmission(db,id,user.id);return submission?Response.json({submission}):Response.json({error:"Not found"},{status:404});}
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){
  if(!isSameOrigin(request))return Response.json({error:"Forbidden"},{status:403}); const [db,user,{id},raw]=await Promise.all([getAuthDatabase(),getRequestUser(request),params,request.json()]);if(!db||!user)return Response.json({error:"Unauthorized"},{status:401});
  const current=await loadSubmission(db,id,user.id);if(!current)return Response.json({error:"Not found"},{status:404});if(!["DRAFT","CHANGES_REQUESTED"].includes(current.state))return Response.json({error:"This submission is locked while editorial review is in progress."},{status:409});
  const input=parseSubmission(raw);if(!input)return Response.json({error:"Write a complete question ending in a question mark and choose a category."},{status:400});const action=(raw as {action?:string}).action;if(action==="submit"){const error=validateForSubmission(input);if(error)return Response.json({error},{status:400});}
  try{await replaceSubmissionContent(db,id,input,action==="submit"?"SUBMITTED":"DRAFT");}catch{return Response.json({error:"Choose a valid category."},{status:400});}return Response.json({id,state:action==="submit"?"SUBMITTED":"DRAFT"});
}
export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){if(!isSameOrigin(request))return new Response("Forbidden",{status:403});const [db,user,{id}]=await Promise.all([getAuthDatabase(),getRequestUser(request),params]);if(!db||!user)return new Response("Unauthorized",{status:401});await db.prepare("DELETE FROM questions WHERE id=? AND publisher_id=? AND submission_state IN ('DRAFT','CHANGES_REQUESTED')").bind(id,user.id).run();return new Response(null,{status:204});}
