ALTER TABLE users ADD COLUMN bio TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN interests TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN avatar_type TEXT NOT NULL DEFAULT 'PRESET' CHECK (avatar_type IN ('PRESET','UPLOAD'));
ALTER TABLE users ADD COLUMN avatar_value TEXT NOT NULL DEFAULT 'explorer';
