import {writeFileSync} from "node:fs";
import {editorialBatchOne} from "../src/data/editorial-batch-one";
const sql=(value:unknown)=>`'${String(value??"").replaceAll("'","''")}'`;
const slugify=(value:string)=>value.toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const lines=["PRAGMA foreign_keys = ON;"];
for(const item of new Set(editorialBatchOne.flatMap(seed=>seed.tags)))lines.push(`INSERT OR IGNORE INTO tags (id,name,slug) VALUES (${sql(`tag-${item}`)},${sql(item)},${sql(item)});`);
editorialBatchOne.forEach((seed,index)=>{
 const id=`reviewed-batch-1-${String(index+1).padStart(3,"0")}`,slug=slugify(seed.question);
 const summary=`This question isolates ${seed.focus}. Tambaya records how the problem acquired its present form, which comparisons shape it, and why its uncertainty remains consequential without proposing an answer.`;
 const stories=[
  ["origins","Origins","Where the question takes shape",`${seed.history}. The specific problem posed by “${seed.question}” emerged only when previously connected concerns were separated and made available to comparison.`],
  ["evolution","Changing frames","How the inquiry developed",`Inquiry into “${seed.question}” has changed with new records, methods, institutions, and participants. Those shifts altered what could be observed and which disagreements appeared fundamental rather than merely technical.`],
  ["why-asked","Persistent uncertainty","Why people keep asking",`${seed.focus}. People return to this question when inherited categories fail to organize a new observation or when a decision exposes competing standards of evidence.`],
  ["why-it-matters","Consequences","Why the framing matters",`${seed.stakes}. Different formulations of “${seed.question}” determine what is measured, whose experience becomes visible, and which connected questions receive attention.`],
  ["where-it-appears","Across fields","Where the question appears",`The question appears across ${seed.category.toLowerCase()}, education, policy, professional practice, and public debate. Its key concepts—${seed.tags.map(value=>value.replaceAll("-"," ")).join(", ")}—do not carry identical meanings in every setting.`],
 ] as const;
 lines.push(`INSERT OR IGNORE INTO questions (id,question_text,slug,publication_state,visibility,claimed_status,verification_state,category_id,category_name,context_summary,public_json,submission_state,publisher_motivation) VALUES (${sql(id)},${sql(seed.question)},${sql(slug)},'DRAFT','PRIVATE',${sql(seed.status)},'PENDING',${sql(seed.categorySlug)},${sql(seed.category)},${sql(summary)},'{}','SUBMITTED','Reviewed expansion batch 1: independently formulated title held for editorial approval.');`);
 lines.push(`INSERT OR IGNORE INTO question_content_sections (id,question_id,section_type,body,provenance,publication_state,answer_leak_state,position) SELECT ${sql(`${id}-summary`)},${sql(id)},'SUMMARY',${sql(summary)},'EDITORIAL','DRAFT','PENDING',0 WHERE EXISTS(SELECT 1 FROM questions WHERE id=${sql(id)});`);
 stories.forEach(([key,kicker,title,body],position)=>{const sectionId=`${id}-story-${key}`;lines.push(`INSERT OR IGNORE INTO question_story_sections (id,question_id,section_key,kicker,title,provenance,answer_leak_state,position) SELECT ${sql(sectionId)},${sql(id)},${sql(key)},${sql(kicker)},${sql(title)},'EDITORIAL','PENDING',${position} WHERE EXISTS(SELECT 1 FROM questions WHERE id=${sql(id)});`);lines.push(`INSERT OR IGNORE INTO question_story_paragraphs (id,section_id,body,position) SELECT ${sql(`${sectionId}-p-0`)},${sql(sectionId)},${sql(body)},0 WHERE EXISTS(SELECT 1 FROM question_story_sections WHERE id=${sql(sectionId)});`);lines.push(`INSERT OR IGNORE INTO question_story_blocks (id,section_id,block_type,data_json,position,answer_leak_state) SELECT ${sql(`${sectionId}-block-0`)},${sql(sectionId)},'PARAGRAPH',${sql(JSON.stringify({text:body}))},0,'PENDING' WHERE EXISTS(SELECT 1 FROM question_story_sections WHERE id=${sql(sectionId)});`);});
 seed.tags.forEach((item,position)=>{lines.push(`INSERT OR IGNORE INTO question_tags(question_id,tag_id) SELECT ${sql(id)},${sql(`tag-${item}`)} WHERE EXISTS(SELECT 1 FROM questions WHERE id=${sql(id)});`);lines.push(`INSERT OR IGNORE INTO question_key_terms(id,question_id,term,description,position) SELECT ${sql(`${id}-term-${position}`)},${sql(id)},${sql(item.replaceAll("-"," ").replace(/\b\w/g,letter=>letter.toUpperCase()))},'A recurring concept whose role in this question changes across methods and settings.',${position} WHERE EXISTS(SELECT 1 FROM questions WHERE id=${sql(id)});`);});
 [["Earlier context",seed.history],["Changing methods",seed.focus],["Present stakes",seed.stakes]].forEach(([date,description],position)=>lines.push(`INSERT OR IGNORE INTO timeline_events(id,question_id,display_date,title,description,position) SELECT ${sql(`${id}-time-${position}`)},${sql(id)},${sql(date)},${sql(position===0?"The problem emerges":position===1?"The frame changes":"The question travels")},${sql(description)},${position} WHERE EXISTS(SELECT 1 FROM questions WHERE id=${sql(id)});`));
 lines.push(`INSERT OR IGNORE INTO question_branches(id,question_id,question_text,relationship_type,position) SELECT ${sql(`${id}-branch-0`)},${sql(id)},${sql(`What evidence would most change how “${seed.question}” is framed?`)},'LEADS_TO',0 WHERE EXISTS(SELECT 1 FROM questions WHERE id=${sql(id)});`);
});
writeFileSync(new URL("../migrations/0038_editorial_batch_one.sql",import.meta.url),`${lines.join("\n")}\n`);
console.log(`Generated editorial batch one with ${editorialBatchOne.length} private review questions.`);
