import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { getAuthDatabase, getCurrentUser } from "@/lib/auth";
import { getBookmarks, getCollections } from "@/lib/library";

export const metadata: Metadata = { title: "Your account" };

export default async function AccountPage({ searchParams }: { searchParams: Promise<{ welcome?: string; created?: string; deleted?: string; error?: string }> }) {
  const user = await getCurrentUser();
  if (!user) redirect("/login");
  const db = await getAuthDatabase();
  if (!db) redirect("/login");
  const [params, bookmarks, collections] = await Promise.all([searchParams,getBookmarks(db,user.id),getCollections(db,user.id)]);
  return <div className="page shell account-page"><header className="page-intro"><span className="eyebrow">Your Tambaya</span><h1>Hello, {user.username}.</h1><p>{params.welcome ? "Your account is ready. Save questions and organise them into private collections." : "Your private place in the question map."}</p></header>{params.error && <p className="auth-error" role="alert">{params.error === "duplicate" ? "You already have a collection with that name." : "Use a collection name of 1–60 characters and a description under 240 characters."}</p>}<section className="library-layout"><div><div className="section-head"><div><span className="eyebrow">Collections</span><h2>Organise your inquiry</h2></div></div><form action="/api/collections" method="post" className="collection-form"><label>Name<input name="name" required maxLength={60} placeholder="Questions about consciousness"/></label><label>Description<textarea name="description" maxLength={240} rows={3} placeholder="An optional note about this collection"/></label><button className="button small">Create collection</button></form><div className="collection-list">{collections.map(collection => <article key={collection.id}><div><h3><Link href={`/collections/${collection.id}`}>{collection.name}</Link></h3><p>{collection.description || "No description yet."}</p><small>{collection.question_count} question{collection.question_count === 1 ? "" : "s"}</small></div><form action={`/api/collections/${collection.id}`} method="post"><button className="text-button">Delete</button></form></article>)}{!collections.length && <div className="empty compact-empty">Create your first collection, then add questions from any question page.</div>}</div></div><aside><span className="eyebrow">Bookmarks</span><h2>Saved questions</h2><div className="bookmark-list">{bookmarks.map(question => <article key={question.id}><div><small>{question.category_name}</small><h3><Link href={`/questions/${question.slug}`}>{question.question_text}</Link></h3></div><form action="/api/bookmarks" method="post"><input type="hidden" name="questionId" value={question.id}/><input type="hidden" name="action" value="remove"/><input type="hidden" name="returnTo" value="/account"/><button className="text-button">Remove</button></form></article>)}{!bookmarks.length && <p className="empty compact-empty">No bookmarks yet. <Link href="/explore">Explore questions →</Link></p>}</div></aside></section><form className="account-logout" action="/api/auth/logout" method="post"><button className="button ghost small">Log out</button></form></div>;
}
